<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Birth Weight Predictions (Code Displayed and Interpreted) – Fathima Shaikh</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Fathima Shaikh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../courses.html"> 
<span class="menu-text">Courses</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Birth Weight Predictions (Code Displayed and Interpreted)</h1>
<p class="subtitle lead">This is a dataset from the North Carolina State Center for Health Statistics. It consists of variables related to the baby, parents, and hospital. This project aims to find out which machine learning model, and which predictors can help predict a baby’s weight at birth. Like the 1st project, I show the code to lasso, ridge regression, PCR, and PLS models I implemented and what I learned from them. I also include some definitions to terms.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-packages" class="level1">
<h1>Load packages</h1>
<p>Download these packages: caret, glmnet, ggplot2, readr, pls, and mgcv.</p>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">Load the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>births <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Downloads/birthsnewone.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456789</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(births)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X Institution.type Plurality.of.birth Gender Race.of.child  Race
1 1                1                  1      2             1 White
2 2                1                  1      2             1 White
3 3                1                  1      2             1 White
4 4                1                  1      2             2 Black
5 5                1                  1      1             2 Black
6 6                1                  1      2             1 White
  Age.of.father Age.of.mother Education.of.father..years.
1            50            24                          12
2            19            18                           9
3            37            35                          17
4            39            31                          11
5            20            19                          11
6            30            27                          16
  Education.of.mother..years. Total.Preg BDead Terms Date.LBirth Month.LBirth
1                          15          2     0     0       32004            3
2                           9          1     0     0           0            0
3                          17          2     0     0      112003           11
4                          16          1     0     0           0            0
5                          12          1     0     0           0            0
6                          16          1     0     0           0            0
  Year.LBirth LOutcome Weeks Prenatal Trimester.Prenatal Visits
1        2004        1    38        3                  1     10
2           0        9    35        3                  1      9
3        2003        1    38        1                  1     20
4           0        9    38        6                  2     12
5           0        9    36        4                  2     10
6           0        9    40        1                  1     20
  Birth.weight.group Marital Birth.Attendant Numchild Month.Term Year.Term
1                  5       2               1        1          0         0
2                  6       2               1        0          0         0
3                  5       1               1        1          0         0
4                  5       2               1        0          0         0
5                  6       2               1        0          0         0
6                  6       1               1        0          0         0
  Low.Birth RaceMom RaceDad Mother.Minority Father.Minority HispMom HispDad
1      Norm       1       2           White        Nonwhite       N       N
2      Norm       1       1           White           White       N       N
3      Norm       1       1           White           White       N       N
4      Norm       2       2        Nonwhite        Nonwhite       N       N
5      Norm       2       1        Nonwhite           White       N       M
6      Norm       1       1           White           White       N       N
  AveCigs Smoker AveDrink Wt.Gain Birth.Weight..g.
1       0     No        0      50         2865.875
2      23   Cigs        0      35         3121.250
3       0     No        0      24         2667.250
4       0     No        0      30         2979.375
5       0     No        0      10         3036.125
6       0     No        0      37         3092.875</code></pre>
</div>
</div>
</section>
<section id="understand-the-variables" class="level2">
<h2 class="anchored" data-anchor-id="understand-the-variables">Understand the variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(births)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7861   39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>UniqueCount <span class="ot">&lt;-</span> <span class="fu">sapply</span>(births, <span class="cf">function</span>(x) <span class="fu">length</span>(<span class="fu">unique</span>(x)))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>FirstFewValues <span class="ot">&lt;-</span> <span class="fu">sapply</span>(births, <span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="fu">head</span>(x, <span class="dv">5</span>), <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>df.unique <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Column =</span> <span class="fu">names</span>(UniqueCount),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">UniqueCount =</span> UniqueCount,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">FirstFewValues =</span> FirstFewValues,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">NULL</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>df.unique</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Column UniqueCount
1                            X        7861
2             Institution.type           3
3           Plurality.of.birth           4
4                       Gender           2
5                Race.of.child           9
6                         Race           3
7                Age.of.father          45
8                Age.of.mother          34
9  Education.of.father..years.          18
10 Education.of.mother..years.          18
11                  Total.Preg          15
12                       BDead           4
13                       Terms          12
14                 Date.LBirth         233
15                Month.LBirth          13
16                 Year.LBirth          27
17                    LOutcome           3
18                       Weeks          28
19                    Prenatal          10
20          Trimester.Prenatal           3
21                      Visits          35
22          Birth.weight.group          10
23                     Marital           2
24             Birth.Attendant           5
25                    Numchild          12
26                  Month.Term          13
27                   Year.Term          24
28                   Low.Birth           2
29                     RaceMom           9
30                     RaceDad           9
31             Mother.Minority           2
32             Father.Minority           2
33                     HispMom           7
34                     HispDad           7
35                     AveCigs          20
36                      Smoker           2
37                    AveDrink           6
38                     Wt.Gain          85
39            Birth.Weight..g.         167
                                   FirstFewValues
1                                   1, 2, 3, 4, 5
2                                   1, 1, 1, 1, 1
3                                   1, 1, 1, 1, 1
4                                   2, 2, 2, 2, 1
5                                   1, 1, 1, 2, 2
6               White, White, White, Black, Black
7                              50, 19, 37, 39, 20
8                              24, 18, 35, 31, 19
9                               12, 9, 17, 11, 11
10                              15, 9, 17, 16, 12
11                                  2, 1, 2, 1, 1
12                                  0, 0, 0, 0, 0
13                                  0, 0, 0, 0, 0
14                         32004, 0, 112003, 0, 0
15                                 3, 0, 11, 0, 0
16                            2004, 0, 2003, 0, 0
17                                  1, 9, 1, 9, 9
18                             38, 35, 38, 38, 36
19                                  3, 3, 1, 6, 4
20                                  1, 1, 1, 2, 2
21                              10, 9, 20, 12, 10
22                                  5, 6, 5, 5, 6
23                                  2, 2, 1, 2, 2
24                                  1, 1, 1, 1, 1
25                                  1, 0, 1, 0, 0
26                                  0, 0, 0, 0, 0
27                                  0, 0, 0, 0, 0
28                   Norm, Norm, Norm, Norm, Norm
29                                  1, 1, 1, 2, 2
30                                  2, 1, 1, 2, 1
31        White, White, White, Nonwhite, Nonwhite
32        Nonwhite, White, White, Nonwhite, White
33                                  N, N, N, N, N
34                                  N, N, N, N, M
35                                 0, 23, 0, 0, 0
36                           No, Cigs, No, No, No
37                                  0, 0, 0, 0, 0
38                             50, 35, 24, 30, 10
39 2865.875, 3121.25, 2667.25, 2979.375, 3036.125</code></pre>
</div>
</div>
<p>There are 39 predictors, and 7861 data points. The column labeled “X” is an index column that r creates. It’s a placeholder index, so you easily access specific rows in your dataset using the index. It can be removed later in data manipulation.</p>
</section>
</section>
<section id="analysis-starts-here" class="level1">
<h1>Analysis Starts Here</h1>
<section id="make-sure-there-are-no-nas" class="level2">
<h2 class="anchored" data-anchor-id="make-sure-there-are-no-nas">Make sure there are no NA’s</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(births))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="split-the-data-into-training-and-testing-groups" class="level2">
<h2 class="anchored" data-anchor-id="split-the-data-into-training-and-testing-groups">Split the data into training and testing groups</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(births)[<span class="dv">1</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>i.train <span class="ot">&lt;-</span> <span class="fu">sample</span>(i,<span class="dv">5000</span>,<span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>B.train <span class="ot">=</span> births[i.train, ]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>B.test <span class="ot">=</span> births[<span class="sc">-</span>i.train, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="start-out-by-testing-a-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="start-out-by-testing-a-linear-model">Start out by testing a linear model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test a linear model on the training data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Birth.Weight..g. <span class="sc">~</span> ., <span class="at">data =</span> B.train)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Birth.Weight..g. ~ ., data = B.train)

Residuals:
    Min      1Q  Median      3Q     Max 
-341.71 -110.67   -0.07  109.94  639.44 

Coefficients: (4 not defined because of singularities)
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 -1.447e+01  9.404e+01  -0.154 0.877708    
X                           -2.965e-04  8.556e-04  -0.347 0.728957    
Institution.type            -5.559e+00  5.677e+00  -0.979 0.327524    
Plurality.of.birth          -4.024e+01  1.121e+01  -3.590 0.000334 ***
Gender                      -9.678e+00  3.938e+00  -2.458 0.014024 *  
Race.of.child               -1.401e+00  4.259e+00  -0.329 0.742224    
RaceOther                    2.202e+01  1.777e+01   1.239 0.215244    
RaceWhite                    2.324e+01  1.184e+01   1.963 0.049672 *  
Age.of.father               -1.050e-01  4.394e-01  -0.239 0.811184    
Age.of.mother                7.303e-01  5.506e-01   1.327 0.184729    
Education.of.father..years.  1.193e+00  1.033e+00   1.154 0.248441    
Education.of.mother..years. -2.347e-01  1.107e+00  -0.212 0.832138    
Total.Preg                   8.432e-01  2.657e+00   0.317 0.751008    
BDead                        5.788e+00  1.477e+01   0.392 0.695273    
Terms                        8.474e-01  4.422e+00   0.192 0.848025    
Date.LBirth                  1.380e-02  5.924e-03   2.330 0.019863 *  
Month.LBirth                -1.386e+02  5.954e+01  -2.329 0.019925 *  
Year.LBirth                         NA         NA      NA       NA    
LOutcome                     1.757e+00  1.378e+00   1.275 0.202240    
Weeks                        1.163e+01  9.640e-01  12.062  &lt; 2e-16 ***
Prenatal                     1.470e+00  2.880e+00   0.511 0.609672    
Trimester.Prenatal           5.674e-01  8.953e+00   0.063 0.949477    
Visits                       6.325e-01  5.818e-01   1.087 0.277082    
Birth.weight.group           4.539e+02  2.337e+00 194.232  &lt; 2e-16 ***
Marital                     -6.235e+00  5.215e+00  -1.196 0.231923    
Birth.Attendant              3.342e+00  3.091e+00   1.081 0.279571    
Numchild                            NA         NA      NA       NA    
Month.Term                   2.393e+00  1.056e+00   2.267 0.023454 *  
Year.Term                   -5.215e-03  4.262e-03  -1.224 0.221104    
Low.BirthNorm                1.840e+01  9.944e+00   1.851 0.064267 .  
RaceMom                             NA         NA      NA       NA    
RaceDad                     -2.745e+00  3.630e+00  -0.756 0.449682    
Mother.MinorityWhite                NA         NA      NA       NA    
Father.MinorityWhite        -3.872e+00  1.187e+01  -0.326 0.744185    
HispMomM                     5.191e+01  7.150e+01   0.726 0.467843    
HispMomN                     4.010e+01  7.072e+01   0.567 0.570709    
HispMomO                     5.907e+01  8.418e+01   0.702 0.482837    
HispMomP                     4.566e+01  7.490e+01   0.610 0.542131    
HispMomS                     1.322e+01  7.179e+01   0.184 0.853885    
HispMomU                     1.278e+02  1.166e+02   1.096 0.272940    
HispDadM                    -1.417e+01  5.844e+01  -0.242 0.808441    
HispDadN                    -1.208e+01  5.799e+01  -0.208 0.834984    
HispDadO                    -2.533e+00  7.262e+01  -0.035 0.972181    
HispDadP                    -2.507e+01  6.131e+01  -0.409 0.682672    
HispDadS                     7.586e+00  5.869e+01   0.129 0.897169    
HispDadU                    -9.431e+01  1.010e+02  -0.933 0.350683    
AveCigs                      8.815e-01  1.140e+00   0.773 0.439512    
SmokerNo                     3.162e+01  1.248e+01   2.535 0.011288 *  
AveDrink                     5.329e+00  1.396e+01   0.382 0.702688    
Wt.Gain                      5.604e-01  1.500e-01   3.736 0.000189 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 137.3 on 4954 degrees of freedom
Multiple R-squared:   0.95, Adjusted R-squared:  0.9495 
F-statistic:  2091 on 45 and 4954 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the linear model and the training data to make predictions of birth weight</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>train_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">data =</span> B.train)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>train_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((births<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> train_pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># do the same, but using testing data</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, B.test)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>test_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((births<span class="sc">$</span>Birth.Weight..g <span class="sc">-</span> test_pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the training and testing mean squared error (average of the sum of squared residuals)</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE:"</span>, train_mse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE: 721481.8 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE:"</span>, test_mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE: 710234.1</code></pre>
</div>
</div>
<p>The training MSE is higher than the testing MSE, which is strange because the model is fit to the training data, not testing. From the linear model, the significant predictors (predictors with a p-value &lt; 0.05) are: Plurality.of.birth, Gender, RaceWhite, Date.LBirth, Month.LBirth, Weeks, Birth.weight.group, Month.Term, Low.BirthNorm, SmokerNo, and Wt.Gain.</p>
<p>This is so cool! These results tell us that the plurality of birth (1 for 1 baby, 1 for twins, 3 for triplets..), gender, and being White have a large role in determining the baby’s birth weight.</p>
</section>
<section id="but-can-we-get-a-better-mse-lets-try-out-a-backward-stepwise-model-and-choose-the-best-predictors." class="level2">
<h2 class="anchored" data-anchor-id="but-can-we-get-a-better-mse-lets-try-out-a-backward-stepwise-model-and-choose-the-best-predictors.">But can we get a better MSE? Let’s try out a backward stepwise model and choose the best predictors.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>stepwise <span class="ot">&lt;-</span> <span class="fu">step</span>(model, <span class="at">direction =</span> <span class="st">"backward"</span>) <span class="co"># the results are very long, unfortunately</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=49270.91
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    Year.LBirth + LOutcome + Weeks + Prenatal + Trimester.Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Numchild + Month.Term + Year.Term + Low.Birth + RaceMom + 
    RaceDad + Mother.Minority + Father.Minority + HispMom + HispDad + 
    AveCigs + Smoker + AveDrink + Wt.Gain


Step:  AIC=49270.91
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    Year.LBirth + LOutcome + Weeks + Prenatal + Trimester.Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Numchild + Month.Term + Year.Term + Low.Birth + RaceMom + 
    RaceDad + Father.Minority + HispMom + HispDad + AveCigs + 
    Smoker + AveDrink + Wt.Gain


Step:  AIC=49270.91
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    Year.LBirth + LOutcome + Weeks + Prenatal + Trimester.Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Numchild + Month.Term + Year.Term + Low.Birth + RaceDad + 
    Father.Minority + HispMom + HispDad + AveCigs + Smoker + 
    AveDrink + Wt.Gain


Step:  AIC=49270.91
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    Year.LBirth + LOutcome + Weeks + Prenatal + Trimester.Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + Father.Minority + 
    HispMom + HispDad + AveCigs + Smoker + AveDrink + Wt.Gain


Step:  AIC=49270.91
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    LOutcome + Weeks + Prenatal + Trimester.Prenatal + Visits + 
    Birth.weight.group + Marital + Birth.Attendant + Month.Term + 
    Year.Term + Low.Birth + RaceDad + Father.Minority + HispMom + 
    HispDad + AveCigs + Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- HispDad                      6     71835  93525388 49263
- HispMom                      6    144476  93598030 49267
- Trimester.Prenatal           1        76  93453629 49269
- Terms                        1       693  93454247 49269
- Education.of.mother..years.  1       848  93454401 49269
- Age.of.father                1      1077  93454630 49269
- Total.Preg                   1      1900  93455453 49269
- Father.Minority              1      2009  93455563 49269
- Race.of.child                1      2041  93455595 49269
- X                            1      2265  93455819 49269
- AveDrink                     1      2749  93456302 49269
- BDead                        1      2895  93456449 49269
- Prenatal                     1      4918  93458471 49269
- RaceDad                      1     10782  93464336 49269
- AveCigs                      1     11274  93464828 49270
- Institution.type             1     18088  93471642 49270
- Birth.Attendant              1     22060  93475614 49270
- Visits                       1     22290  93475844 49270
- Education.of.father..years.  1     25134  93478688 49270
- Marital                      1     26964  93480518 49270
- Year.Term                    1     28251  93481804 49270
- LOutcome                     1     30684  93484237 49271
- Age.of.mother                1     33194  93486748 49271
&lt;none&gt;                                      93453554 49271
- Race                         2     98382  93551936 49272
- Low.Birth                    1     64614  93518168 49272
- Month.Term                   1     96920  93550473 49274
- Month.LBirth                 1    102281  93555834 49274
- Date.LBirth                  1    102384  93555937 49274
- Gender                       1    113929  93567483 49275
- Smoker                       1    121188  93574742 49275
- Plurality.of.birth           1    243163  93696716 49282
- Wt.Gain                      1    263341  93716895 49283
- Weeks                        1   2744656  96198210 49414
- Birth.weight.group           1 711671687 805125240 60037

Step:  AIC=49262.75
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    LOutcome + Weeks + Prenatal + Trimester.Prenatal + Visits + 
    Birth.weight.group + Marital + Birth.Attendant + Month.Term + 
    Year.Term + Low.Birth + RaceDad + Father.Minority + HispMom + 
    AveCigs + Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- HispMom                      6    107874  93633263 49257
- Trimester.Prenatal           1       357  93525746 49261
- Terms                        1       854  93526242 49261
- Age.of.father                1       999  93526387 49261
- Education.of.mother..years.  1      1247  93526635 49261
- Race.of.child                1      1395  93526783 49261
- Total.Preg                   1      1853  93527242 49261
- X                            1      2618  93528006 49261
- AveDrink                     1      2794  93528183 49261
- Father.Minority              1      3039  93528428 49261
- BDead                        1      3063  93528451 49261
- Prenatal                     1      3872  93529260 49261
- AveCigs                      1     11261  93536649 49261
- RaceDad                      1     12842  93538231 49261
- Institution.type             1     17979  93543368 49262
- Birth.Attendant              1     20942  93546330 49262
- Education.of.father..years.  1     23580  93548968 49262
- Visits                       1     24631  93550019 49262
- Marital                      1     26407  93551795 49262
- Year.Term                    1     28389  93553777 49262
- LOutcome                     1     30194  93555582 49262
- Age.of.mother                1     32947  93558335 49263
&lt;none&gt;                                      93525388 49263
- Low.Birth                    1     67073  93592461 49264
- Race                         2    106534  93631923 49264
- Month.Term                   1     94720  93620108 49266
- Month.LBirth                 1    101556  93626944 49266
- Date.LBirth                  1    101660  93627048 49266
- Gender                       1    112824  93638213 49267
- Smoker                       1    123060  93648449 49267
- Plurality.of.birth           1    242055  93767444 49274
- Wt.Gain                      1    263032  93788421 49275
- Weeks                        1   2743738  96269127 49405
- Birth.weight.group           1 712280260 805805649 60029

Step:  AIC=49256.52
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    LOutcome + Weeks + Prenatal + Trimester.Prenatal + Visits + 
    Birth.weight.group + Marital + Birth.Attendant + Month.Term + 
    Year.Term + Low.Birth + RaceDad + Father.Minority + AveCigs + 
    Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Trimester.Prenatal           1       239  93633502 49255
- Age.of.father                1       507  93633770 49255
- Race.of.child                1       780  93634043 49255
- Terms                        1      1107  93634370 49255
- Total.Preg                   1      1215  93634478 49255
- Father.Minority              1      2019  93635282 49255
- AveDrink                     1      2362  93635625 49255
- X                            1      2413  93635676 49255
- Education.of.mother..years.  1      3883  93637146 49255
- BDead                        1      4292  93637555 49255
- Prenatal                     1      5090  93638353 49255
- AveCigs                      1     10646  93643909 49255
- RaceDad                      1     12092  93645355 49255
- Education.of.father..years.  1     15184  93648447 49255
- Institution.type             1     18260  93651523 49255
- Birth.Attendant              1     20945  93654208 49256
- Visits                       1     23412  93656675 49256
- Year.Term                    1     27779  93661042 49256
- Marital                      1     27885  93661148 49256
- LOutcome                     1     28892  93662155 49256
- Age.of.mother                1     31504  93664767 49256
&lt;none&gt;                                      93633263 49257
- Low.Birth                    1     66920  93700183 49258
- Race                         2    107086  93740349 49258
- Month.Term                   1     97040  93730303 49260
- Month.LBirth                 1    103555  93736818 49260
- Date.LBirth                  1    103675  93736938 49260
- Gender                       1    113196  93746459 49261
- Smoker                       1    134589  93767852 49262
- Plurality.of.birth           1    241539  93874801 49267
- Wt.Gain                      1    256311  93889573 49268
- Weeks                        1   2761996  96395259 49400
- Birth.weight.group           1 712986585 806619847 60022

Step:  AIC=49254.53
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.father + Age.of.mother + 
    Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Terms + Date.LBirth + Month.LBirth + 
    LOutcome + Weeks + Prenatal + Visits + Birth.weight.group + 
    Marital + Birth.Attendant + Month.Term + Year.Term + Low.Birth + 
    RaceDad + Father.Minority + AveCigs + Smoker + AveDrink + 
    Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Age.of.father                1       513  93634016 49253
- Race.of.child                1       764  93634267 49253
- Terms                        1      1109  93634612 49253
- Total.Preg                   1      1223  93634725 49253
- Father.Minority              1      2029  93635531 49253
- AveDrink                     1      2362  93635864 49253
- X                            1      2462  93635965 49253
- Education.of.mother..years.  1      3885  93637387 49253
- BDead                        1      4329  93637831 49253
- AveCigs                      1     10662  93644164 49253
- RaceDad                      1     12180  93645682 49253
- Education.of.father..years.  1     15251  93648753 49253
- Institution.type             1     18370  93651873 49254
- Prenatal                     1     18577  93652080 49254
- Birth.Attendant              1     20855  93654358 49254
- Visits                       1     23244  93656747 49254
- Marital                      1     27719  93661222 49254
- Year.Term                    1     27836  93661338 49254
- LOutcome                     1     28876  93662378 49254
- Age.of.mother                1     31565  93665067 49254
&lt;none&gt;                                      93633502 49255
- Low.Birth                    1     66940  93700443 49256
- Race                         2    107108  93740610 49256
- Month.Term                   1     97040  93730542 49258
- Month.LBirth                 1    103459  93736961 49258
- Date.LBirth                  1    103580  93737083 49258
- Gender                       1    113153  93746656 49259
- Smoker                       1    134687  93768190 49260
- Plurality.of.birth           1    241303  93874806 49265
- Wt.Gain                      1    256181  93889684 49266
- Weeks                        1   2761827  96395330 49398
- Birth.weight.group           1 712988733 806622235 60020

Step:  AIC=49252.56
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race.of.child + Race + Age.of.mother + Education.of.father..years. + 
    Education.of.mother..years. + Total.Preg + BDead + Terms + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + Father.Minority + 
    AveCigs + Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Race.of.child                1       754  93634769 49251
- Terms                        1      1159  93635174 49251
- Total.Preg                   1      1173  93635188 49251
- Father.Minority              1      2026  93636042 49251
- AveDrink                     1      2421  93636437 49251
- X                            1      2430  93636446 49251
- Education.of.mother..years.  1      3775  93637791 49251
- BDead                        1      4322  93638337 49251
- AveCigs                      1     10623  93644639 49251
- RaceDad                      1     12248  93646264 49251
- Education.of.father..years.  1     14978  93648994 49251
- Institution.type             1     18394  93652409 49252
- Prenatal                     1     18660  93652676 49252
- Birth.Attendant              1     21165  93655181 49252
- Visits                       1     23241  93657257 49252
- Marital                      1     27655  93661670 49252
- Year.Term                    1     28006  93662022 49252
- LOutcome                     1     28838  93662854 49252
&lt;none&gt;                                      93634016 49253
- Age.of.mother                1     46405  93680421 49253
- Low.Birth                    1     66823  93700839 49254
- Race                         2    107060  93741076 49254
- Month.Term                   1     97175  93731191 49256
- Month.LBirth                 1    103335  93737351 49256
- Date.LBirth                  1    103456  93737472 49256
- Gender                       1    113311  93747327 49257
- Smoker                       1    134933  93768949 49258
- Plurality.of.birth           1    241597  93875612 49263
- Wt.Gain                      1    256611  93890627 49264
- Weeks                        1   2761734  96395750 49396
- Birth.weight.group           1 713139858 806773873 60019

Step:  AIC=49250.6
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race + Age.of.mother + Education.of.father..years. + 
    Education.of.mother..years. + Total.Preg + BDead + Terms + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + Father.Minority + 
    AveCigs + Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Terms                        1      1141  93635911 49249
- Total.Preg                   1      1185  93635954 49249
- X                            1      2384  93637153 49249
- AveDrink                     1      2420  93637190 49249
- Father.Minority              1      3169  93637938 49249
- Education.of.mother..years.  1      3700  93638469 49249
- BDead                        1      4481  93639250 49249
- AveCigs                      1     10647  93645416 49249
- Education.of.father..years.  1     14753  93649522 49249
- Institution.type             1     18346  93653116 49250
- Prenatal                     1     18699  93653468 49250
- Birth.Attendant              1     21198  93655968 49250
- RaceDad                      1     23135  93657905 49250
- Visits                       1     23323  93658093 49250
- Marital                      1     27652  93662421 49250
- Year.Term                    1     28259  93663029 49250
- LOutcome                     1     28881  93663650 49250
&lt;none&gt;                                      93634769 49251
- Age.of.mother                1     46296  93681066 49251
- Low.Birth                    1     66328  93701097 49252
- Race                         2    122698  93757467 49253
- Month.Term                   1     97566  93732336 49254
- Month.LBirth                 1    103465  93738235 49254
- Date.LBirth                  1    103586  93738355 49254
- Gender                       1    113302  93748071 49255
- Smoker                       1    134829  93769599 49256
- Plurality.of.birth           1    241733  93876502 49261
- Wt.Gain                      1    256559  93891328 49262
- Weeks                        1   2768546  96403315 49394
- Birth.weight.group           1 713358214 806992983 60018

Step:  AIC=49248.66
Birth.Weight..g. ~ X + Institution.type + Plurality.of.birth + 
    Gender + Race + Age.of.mother + Education.of.father..years. + 
    Education.of.mother..years. + Total.Preg + BDead + Date.LBirth + 
    Month.LBirth + LOutcome + Weeks + Prenatal + Visits + Birth.weight.group + 
    Marital + Birth.Attendant + Month.Term + Year.Term + Low.Birth + 
    RaceDad + Father.Minority + AveCigs + Smoker + AveDrink + 
    Wt.Gain

                              Df Sum of Sq       RSS   AIC
- X                            1      2408  93638319 49247
- AveDrink                     1      2470  93638381 49247
- Father.Minority              1      3208  93639119 49247
- Education.of.mother..years.  1      3274  93639184 49247
- BDead                        1      3941  93639851 49247
- Total.Preg                   1      5199  93641109 49247
- AveCigs                      1     10766  93646677 49247
- Education.of.father..years.  1     14738  93650648 49247
- Institution.type             1     18066  93653977 49248
- Prenatal                     1     18476  93654386 49248
- Birth.Attendant              1     20955  93656865 49248
- RaceDad                      1     23440  93659351 49248
- Visits                       1     23938  93659849 49248
- Marital                      1     27473  93663383 49248
- LOutcome                     1     29336  93665247 49248
- Year.Term                    1     29376  93665287 49248
&lt;none&gt;                                      93635911 49249
- Age.of.mother                1     45226  93681137 49249
- Low.Birth                    1     66214  93702124 49250
- Race                         2    123410  93759320 49251
- Month.Term                   1     97407  93733318 49252
- Month.LBirth                 1    102669  93738580 49252
- Date.LBirth                  1    102801  93738711 49252
- Gender                       1    114014  93749925 49253
- Smoker                       1    134755  93770666 49254
- Plurality.of.birth           1    243339  93879250 49260
- Wt.Gain                      1    257362  93893272 49260
- Weeks                        1   2768511  96404421 49392
- Birth.weight.group           1 713660859 807296769 60018

Step:  AIC=49246.79
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Prenatal + Visits + Birth.weight.group + Marital + 
    Birth.Attendant + Month.Term + Year.Term + Low.Birth + RaceDad + 
    Father.Minority + AveCigs + Smoker + AveDrink + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- AveDrink                     1      2494  93640813 49245
- Education.of.mother..years.  1      3181  93641500 49245
- Father.Minority              1      3202  93641521 49245
- BDead                        1      3966  93642285 49245
- Total.Preg                   1      5201  93643520 49245
- AveCigs                      1     10837  93649156 49245
- Education.of.father..years.  1     14522  93652841 49246
- Institution.type             1     18113  93656432 49246
- Prenatal                     1     18736  93657055 49246
- Birth.Attendant              1     21002  93659321 49246
- RaceDad                      1     23407  93661726 49246
- Visits                       1     23909  93662228 49246
- Marital                      1     27497  93665816 49246
- LOutcome                     1     29322  93667641 49246
- Year.Term                    1     29655  93667974 49246
&lt;none&gt;                                      93638319 49247
- Age.of.mother                1     45317  93683636 49247
- Low.Birth                    1     66105  93704424 49248
- Race                         2    123002  93761320 49249
- Month.Term                   1     97830  93736148 49250
- Month.LBirth                 1    102519  93740838 49250
- Date.LBirth                  1    102653  93740972 49250
- Gender                       1    113413  93751732 49251
- Smoker                       1    134650  93772969 49252
- Plurality.of.birth           1    242577  93880895 49258
- Wt.Gain                      1    256808  93895126 49258
- Weeks                        1   2768310  96406628 49390
- Birth.weight.group           1 713723815 807362134 60016

Step:  AIC=49244.92
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Prenatal + Visits + Birth.weight.group + Marital + 
    Birth.Attendant + Month.Term + Year.Term + Low.Birth + RaceDad + 
    Father.Minority + AveCigs + Smoker + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Father.Minority              1      3149  93643962 49243
- Education.of.mother..years.  1      3319  93644132 49243
- BDead                        1      3934  93644747 49243
- Total.Preg                   1      5173  93645986 49243
- AveCigs                      1     10858  93651671 49243
- Education.of.father..years.  1     14688  93655501 49244
- Institution.type             1     18115  93658928 49244
- Prenatal                     1     18958  93659771 49244
- Birth.Attendant              1     20943  93661756 49244
- RaceDad                      1     23340  93664153 49244
- Visits                       1     24346  93665159 49244
- Marital                      1     27361  93668174 49244
- Year.Term                    1     29368  93670181 49244
- LOutcome                     1     29501  93670314 49244
&lt;none&gt;                                      93640813 49245
- Age.of.mother                1     45252  93686065 49245
- Low.Birth                    1     66106  93706919 49246
- Race                         2    122619  93763432 49247
- Month.Term                   1     97738  93738551 49248
- Month.LBirth                 1    102696  93743509 49248
- Date.LBirth                  1    102835  93743648 49248
- Gender                       1    113266  93754078 49249
- Smoker                       1    133702  93774515 49250
- Plurality.of.birth           1    242795  93883608 49256
- Wt.Gain                      1    256775  93897588 49257
- Weeks                        1   2767525  96408338 49389
- Birth.weight.group           1 713814015 807454828 60015

Step:  AIC=49243.09
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Education.of.mother..years. + 
    Total.Preg + BDead + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Prenatal + Visits + Birth.weight.group + Marital + 
    Birth.Attendant + Month.Term + Year.Term + Low.Birth + RaceDad + 
    AveCigs + Smoker + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Education.of.mother..years.  1      3130  93647092 49241
- BDead                        1      3856  93647818 49241
- Total.Preg                   1      5409  93649371 49241
- AveCigs                      1     11353  93655315 49242
- Education.of.father..years.  1     14720  93658683 49242
- Institution.type             1     18049  93662012 49242
- Prenatal                     1     18581  93662543 49242
- Birth.Attendant              1     21268  93665230 49242
- RaceDad                      1     22026  93665989 49242
- Visits                       1     24329  93668291 49242
- Marital                      1     25265  93669228 49242
- LOutcome                     1     28944  93672907 49243
- Year.Term                    1     29239  93673202 49243
&lt;none&gt;                                      93643962 49243
- Age.of.mother                1     43892  93687855 49243
- Low.Birth                    1     65804  93709766 49245
- Month.Term                   1     97887  93741849 49246
- Month.LBirth                 1    101921  93745884 49247
- Date.LBirth                  1    102058  93746020 49247
- Gender                       1    111930  93755892 49247
- Smoker                       1    134639  93778602 49248
- Plurality.of.birth           1    242504  93886467 49254
- Race                         2    290670  93934632 49255
- Wt.Gain                      1    256914  93900877 49255
- Weeks                        1   2764662  96408625 49387
- Birth.weight.group           1 714503432 808147394 60017

Step:  AIC=49241.25
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Total.Preg + 
    BDead + Date.LBirth + Month.LBirth + LOutcome + Weeks + Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + AveCigs + 
    Smoker + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- BDead                        1      3854  93650946 49239
- Total.Preg                   1      7060  93654153 49240
- AveCigs                      1     11437  93658529 49240
- Education.of.father..years.  1     12356  93659448 49240
- Institution.type             1     18216  93665308 49240
- Prenatal                     1     19603  93666695 49240
- Birth.Attendant              1     21098  93668190 49240
- RaceDad                      1     21936  93669028 49240
- Marital                      1     23457  93670549 49241
- Visits                       1     23771  93670863 49241
- LOutcome                     1     28338  93675430 49241
- Year.Term                    1     30658  93677750 49241
&lt;none&gt;                                      93647092 49241
- Age.of.mother                1     40911  93688003 49241
- Low.Birth                    1     65382  93712475 49243
- Month.Term                   1     97763  93744855 49244
- Month.LBirth                 1    101808  93748900 49245
- Date.LBirth                  1    101937  93749029 49245
- Gender                       1    111657  93758749 49245
- Smoker                       1    134087  93781179 49246
- Plurality.of.birth           1    244812  93891905 49252
- Wt.Gain                      1    254790  93901883 49253
- Race                         2    296705  93943797 49253
- Weeks                        1   2768356  96415448 49385
- Birth.weight.group           1 714655103 808302195 60016

Step:  AIC=49239.46
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Total.Preg + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + AveCigs + 
    Smoker + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Total.Preg                   1      9201  93660148 49238
- AveCigs                      1     11185  93662132 49238
- Education.of.father..years.  1     12354  93663300 49238
- Institution.type             1     18272  93669218 49238
- Prenatal                     1     19331  93670277 49238
- Birth.Attendant              1     20884  93671830 49239
- RaceDad                      1     22677  93673623 49239
- Marital                      1     23297  93674243 49239
- Visits                       1     24011  93674958 49239
- LOutcome                     1     28125  93679071 49239
- Year.Term                    1     32928  93683874 49239
&lt;none&gt;                                      93650946 49239
- Age.of.mother                1     40063  93691009 49240
- Low.Birth                    1     65898  93716844 49241
- Month.Term                   1     99340  93750286 49243
- Month.LBirth                 1    101027  93751973 49243
- Date.LBirth                  1    101153  93752099 49243
- Gender                       1    111914  93762860 49243
- Smoker                       1    133844  93784790 49245
- Plurality.of.birth           1    246645  93897591 49251
- Wt.Gain                      1    253520  93904466 49251
- Race                         2    296261  93947207 49251
- Weeks                        1   2766851  96417797 49383
- Birth.weight.group           1 715517563 809168509 60020

Step:  AIC=49237.95
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Education.of.father..years. + Date.LBirth + 
    Month.LBirth + LOutcome + Weeks + Prenatal + Visits + Birth.weight.group + 
    Marital + Birth.Attendant + Month.Term + Year.Term + Low.Birth + 
    RaceDad + AveCigs + Smoker + Wt.Gain

                              Df Sum of Sq       RSS   AIC
- Education.of.father..years.  1      9841  93669988 49236
- AveCigs                      1     11173  93671320 49237
- Institution.type             1     17956  93678103 49237
- Prenatal                     1     20926  93681073 49237
- Birth.Attendant              1     21827  93681974 49237
- RaceDad                      1     22253  93682401 49237
- Marital                      1     22932  93683080 49237
- Visits                       1     23363  93683511 49237
- Year.Term                    1     24274  93684421 49237
- LOutcome                     1     30218  93690366 49238
&lt;none&gt;                                      93660148 49238
- Age.of.mother                1     52197  93712345 49239
- Low.Birth                    1     65278  93725425 49239
- Month.Term                   1     98352  93758500 49241
- Gender                       1    110357  93770505 49242
- Smoker                       1    130899  93791046 49243
- Month.LBirth                 1    131742  93791889 49243
- Date.LBirth                  1    132164  93792312 49243
- Plurality.of.birth           1    243342  93903489 49249
- Race                         2    289461  93949609 49249
- Wt.Gain                      1    252100  93912248 49249
- Weeks                        1   2761147  96421294 49381
- Birth.weight.group           1 716394675 810054822 60023

Step:  AIC=49236.48
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Prenatal + Visits + Birth.weight.group + Marital + 
    Birth.Attendant + Month.Term + Year.Term + Low.Birth + RaceDad + 
    AveCigs + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- AveCigs             1     10876  93680865 49235
- Prenatal            1     16490  93686479 49235
- Institution.type    1     16988  93686976 49235
- RaceDad             1     19967  93689956 49236
- Birth.Attendant     1     22401  93692390 49236
- Year.Term           1     24424  93694413 49236
- Visits              1     25198  93695186 49236
- LOutcome            1     31040  93701028 49236
- Marital             1     32542  93702530 49236
&lt;none&gt;                             93669988 49236
- Low.Birth           1     64569  93734558 49238
- Age.of.mother       1     69733  93739721 49238
- Month.Term          1     99348  93769337 49240
- Gender              1    111043  93781032 49240
- Month.LBirth        1    128894  93798882 49241
- Date.LBirth         1    129305  93799293 49241
- Smoker              1    130464  93800453 49241
- Plurality.of.birth  1    240900  93910889 49247
- Race                2    282031  93952019 49248
- Wt.Gain             1    261667  93931655 49248
- Weeks               1   2759646  96429635 49380
- Birth.weight.group  1 716728836 810398824 60023

Step:  AIC=49235.06
Birth.Weight..g. ~ Institution.type + Plurality.of.birth + Gender + 
    Race + Age.of.mother + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Prenatal + Visits + Birth.weight.group + Marital + 
    Birth.Attendant + Month.Term + Year.Term + Low.Birth + RaceDad + 
    Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- Institution.type    1     16937  93697802 49234
- Prenatal            1     17921  93698786 49234
- RaceDad             1     20332  93701196 49234
- Birth.Attendant     1     20966  93701831 49234
- Year.Term           1     24484  93705348 49234
- Visits              1     25261  93706126 49234
- LOutcome            1     30859  93711724 49235
- Marital             1     34003  93714867 49235
&lt;none&gt;                             93680865 49235
- Low.Birth           1     64523  93745387 49236
- Age.of.mother       1     71193  93752058 49237
- Month.Term          1     98790  93779655 49238
- Gender              1    111363  93792227 49239
- Month.LBirth        1    130126  93810991 49240
- Date.LBirth         1    130521  93811386 49240
- Plurality.of.birth  1    241872  93922737 49246
- Smoker              1    242983  93923848 49246
- Race                2    287000  93967865 49246
- Wt.Gain             1    261574  93942439 49247
- Weeks               1   2759522  96440387 49378
- Birth.weight.group  1 717126874 810807739 60024

Step:  AIC=49233.96
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Prenatal + 
    Visits + Birth.weight.group + Marital + Birth.Attendant + 
    Month.Term + Year.Term + Low.Birth + RaceDad + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- Prenatal            1     16659  93714460 49233
- Birth.Attendant     1     17184  93714986 49233
- RaceDad             1     20667  93718468 49233
- Year.Term           1     24802  93722603 49233
- Visits              1     24949  93722751 49233
- LOutcome            1     31275  93729077 49234
- Marital             1     34093  93731894 49234
&lt;none&gt;                             93697802 49234
- Low.Birth           1     64855  93762657 49235
- Age.of.mother       1     69059  93766861 49236
- Month.Term          1     99803  93797605 49237
- Gender              1    111532  93809334 49238
- Month.LBirth        1    130014  93827816 49239
- Date.LBirth         1    130433  93828235 49239
- Smoker              1    241271  93939073 49245
- Plurality.of.birth  1    241620  93939422 49245
- Race                2    285977  93983779 49245
- Wt.Gain             1    259327  93957128 49246
- Weeks               1   2758699  96456501 49377
- Birth.weight.group  1 717140364 810838166 60022

Step:  AIC=49232.85
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Visits + 
    Birth.weight.group + Marital + Birth.Attendant + Month.Term + 
    Year.Term + Low.Birth + RaceDad + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- Visits              1     12771  93727231 49232
- Birth.Attendant     1     17766  93732226 49232
- RaceDad             1     20119  93734579 49232
- Year.Term           1     23837  93738297 49232
- Marital             1     28607  93743068 49232
- LOutcome            1     31764  93746224 49233
&lt;none&gt;                             93714460 49233
- Age.of.mother       1     64513  93778973 49234
- Low.Birth           1     65014  93779475 49234
- Month.Term          1     98329  93812789 49236
- Gender              1    111020  93825480 49237
- Month.LBirth        1    132699  93847159 49238
- Date.LBirth         1    133168  93847628 49238
- Plurality.of.birth  1    236391  93950851 49243
- Smoker              1    237139  93951599 49243
- Race                2    283283  93997743 49244
- Wt.Gain             1    253698  93968159 49244
- Weeks               1   2815836  96530296 49379
- Birth.weight.group  1 717312360 811026821 60021

Step:  AIC=49231.53
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Birth.weight.group + 
    Marital + Birth.Attendant + Month.Term + Year.Term + Low.Birth + 
    RaceDad + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- Birth.Attendant     1     16817  93744048 49230
- RaceDad             1     19646  93746877 49231
- Year.Term           1     22864  93750096 49231
- LOutcome            1     32561  93759793 49231
- Marital             1     33397  93760628 49231
&lt;none&gt;                             93727231 49232
- Low.Birth           1     65904  93793135 49233
- Age.of.mother       1     70089  93797320 49233
- Month.Term          1     99064  93826295 49235
- Gender              1    109353  93836585 49235
- Month.LBirth        1    130476  93857707 49236
- Date.LBirth         1    130942  93858173 49237
- Plurality.of.birth  1    225729  93952961 49242
- Smoker              1    236939  93964170 49242
- Race                2    277059  94004290 49242
- Wt.Gain             1    261273  93988504 49243
- Weeks               1   2852807  96580039 49379
- Birth.weight.group  1 720155397 813882628 60037

Step:  AIC=49230.43
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Birth.weight.group + 
    Marital + Month.Term + Year.Term + Low.Birth + RaceDad + 
    Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- RaceDad             1     18974  93763023 49229
- Year.Term           1     22853  93766902 49230
- LOutcome            1     32265  93776313 49230
- Marital             1     35297  93779346 49230
&lt;none&gt;                             93744048 49230
- Age.of.mother       1     66244  93810293 49232
- Low.Birth           1     66786  93810834 49232
- Month.Term          1     98058  93842106 49234
- Gender              1    108369  93852417 49234
- Month.LBirth        1    132256  93876304 49235
- Date.LBirth         1    132707  93876755 49236
- Plurality.of.birth  1    229890  93973938 49241
- Smoker              1    235464  93979513 49241
- Race                2    280307  94024355 49241
- Wt.Gain             1    261945  94005993 49242
- Weeks               1   2856162  96600210 49378
- Birth.weight.group  1 720222651 813966699 60035

Step:  AIC=49229.44
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Birth.weight.group + 
    Marital + Month.Term + Year.Term + Low.Birth + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
- Year.Term           1     22239  93785262 49229
- LOutcome            1     32342  93795365 49229
- Marital             1     35310  93798333 49229
&lt;none&gt;                             93763023 49229
- Age.of.mother       1     64623  93827646 49231
- Low.Birth           1     64672  93827695 49231
- Month.Term          1     98066  93861089 49233
- Gender              1    107746  93870769 49233
- Month.LBirth        1    132797  93895820 49235
- Date.LBirth         1    133254  93896277 49235
- Plurality.of.birth  1    228469  93991492 49240
- Smoker              1    234739  93997761 49240
- Wt.Gain             1    260187  94023210 49241
- Race                2    411765  94174787 49247
- Weeks               1   2850830  96613852 49377
- Birth.weight.group  1 721715962 815478985 60042

Step:  AIC=49228.63
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + Age.of.mother + 
    Date.LBirth + Month.LBirth + LOutcome + Weeks + Birth.weight.group + 
    Marital + Month.Term + Low.Birth + Smoker + Wt.Gain

                     Df Sum of Sq       RSS   AIC
&lt;none&gt;                             93785262 49229
- Marital             1     38287  93823550 49229
- Age.of.mother       1     57325  93842587 49230
- LOutcome            1     59406  93844668 49230
- Low.Birth           1     64835  93850097 49230
- Month.Term          1     77781  93863043 49231
- Gender              1    107034  93892296 49232
- Month.LBirth        1    168630  93953893 49236
- Date.LBirth         1    169519  93954781 49236
- Plurality.of.birth  1    227383  94012645 49239
- Smoker              1    244280  94029542 49240
- Wt.Gain             1    259786  94045048 49240
- Race                2    423687  94208949 49247
- Weeks               1   2844759  96630021 49376
- Birth.weight.group  1 721813693 815598955 60041</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stepwise) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Birth.Weight..g. ~ Plurality.of.birth + Gender + 
    Race + Age.of.mother + Date.LBirth + Month.LBirth + LOutcome + 
    Weeks + Birth.weight.group + Marital + Month.Term + Low.Birth + 
    Smoker + Wt.Gain, data = B.train)

Residuals:
    Min      1Q  Median      3Q     Max 
-340.96 -110.87    0.41  109.64  647.17 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         2.223e+01  4.041e+01   0.550 0.582214    
Plurality.of.birth -3.832e+01  1.102e+01  -3.476 0.000513 ***
Gender             -9.355e+00  3.923e+00  -2.385 0.017118 *  
RaceOther           8.162e+00  1.024e+01   0.797 0.425643    
RaceWhite           2.433e+01  5.329e+00   4.565 5.11e-06 ***
Age.of.mother       6.446e-01  3.693e-01   1.745 0.080979 .  
Date.LBirth         1.619e-02  5.393e-03   3.001 0.002700 ** 
Month.LBirth       -1.624e+02  5.426e+01  -2.994 0.002771 ** 
LOutcome            2.291e+00  1.290e+00   1.777 0.075663 .  
Weeks               1.173e+01  9.540e-01  12.295  &lt; 2e-16 ***
Birth.weight.group  4.542e+02  2.319e+00 195.855  &lt; 2e-16 ***
Marital            -6.925e+00  4.855e+00  -1.426 0.153808    
Month.Term          1.725e+00  8.486e-01   2.033 0.042096 *  
Low.BirthNorm       1.838e+01  9.904e+00   1.856 0.063483 .  
SmokerNo            2.467e+01  6.847e+00   3.603 0.000318 ***
Wt.Gain             5.499e-01  1.480e-01   3.716 0.000205 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 137.2 on 4984 degrees of freedom
Multiple R-squared:  0.9498,    Adjusted R-squared:  0.9496 
F-statistic:  6286 on 15 and 4984 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the summary of the stepwise model, you can see a similar outcome as the linear model, with Plurality.of.birth, Gender, Race, Weeks, Birth.weight.group, Father.Minority, Smoker, and Wt.Gain being the top significant predictors.</p>
</section>
</section>
<section id="now-well-create-a-refined-step-model-using-the-top-8-most-significant-predictors." class="level1">
<h1>Now, we’ll create a refined step model using the top 8 most significant predictors.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Birth.Weight..g. <span class="sc">~</span> Plurality.of.birth <span class="sc">+</span> Gender <span class="sc">+</span> Race <span class="sc">+</span> Weeks <span class="sc">+</span> Birth.weight.group <span class="sc">+</span> Father.Minority <span class="sc">+</span> Smoker <span class="sc">+</span> Wt.Gain , <span class="at">data =</span> B.train)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict birth weight using the step model and the training data</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>step_train_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, B.train)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>step_train_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((births<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> step_train_pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Do the same but with the testing data</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>step_test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, B.test)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>step_test_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((births<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> step_test_pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE:"</span>, step_train_mse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE: 721443.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE:"</span>, step_test_mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE: 709755.3</code></pre>
</div>
</div>
<p>Again the training MSE is higher than the testing MSE, which is unusual. The MSE is lower here than the linear model with all predictors.</p>
<section id="we-still-want-a-lower-mse.-lets-try-out-ridge-regression-with-the-complete-data-births." class="level2">
<h2 class="anchored" data-anchor-id="we-still-want-a-lower-mse.-lets-try-out-ridge-regression-with-the-complete-data-births.">We still want a lower MSE. Let’s try out ridge regression with the complete data (births).</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Do a log transformation on the response. A log transformation can linearize the relationship between response and dependent variables, making linear regression more effective.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>birthsLog <span class="ot">&lt;-</span> <span class="fu">transform</span>(births, <span class="at">lWeight =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(births<span class="sc">$</span>Birth.Weight..g.)))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>birthsLog <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthsLog, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Birth.Weight..g., X)) <span class="co"># remove the original response variable and the index </span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>B.testLog <span class="ot">&lt;-</span> <span class="fu">transform</span>(B.test, <span class="at">lWeight =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(B.test<span class="sc">$</span>Birth.Weight..g.)))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>B.testLog <span class="ot">&lt;-</span> <span class="fu">subset</span>(B.testLog, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Birth.Weight..g., X))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Omit the NA's</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>births2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(birthsLog)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>B.test2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(B.testLog)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the model matrices for full and testing data</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>x_full <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lWeight <span class="sc">~</span> ., <span class="at">data =</span> births2)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>y_full <span class="ot">&lt;-</span> births2<span class="sc">$</span>lWeight</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lWeight <span class="sc">~</span> ., <span class="at">data =</span> B.test2)</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> B.test2<span class="sc">$</span>lWeight</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Ridge Regression</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>lambda.v <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">lambda =</span> lambda.v)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross-validation to find best lambda</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>cv.output <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>qplot <span class="ot">&lt;-</span> <span class="fu">qplot</span>(<span class="fu">log</span>(cv.output<span class="sc">$</span>lambda),cv.output<span class="sc">$</span>cvsd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `qplot()` was deprecated in ggplot2 3.4.0.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bestlamb.cv <span class="ot">&lt;-</span> cv.output<span class="sc">$</span>lambda.min</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model with the best lambda</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>best_ridge <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">lambda =</span> bestlamb.cv)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>pred.births2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(best_ridge, <span class="at">newx =</span> x_full, <span class="at">s =</span> bestlamb.cv, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>pred.Btest2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(best_ridge, <span class="at">newx =</span> x_test, <span class="at">s =</span> bestlamb.cv, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MSE's</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>MSE.births2 <span class="ot">&lt;-</span> <span class="fu">mean</span>((y_full <span class="sc">-</span> pred.births2)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Full data MSE</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>MSE.Btest2 <span class="ot">&lt;-</span> <span class="fu">mean</span>((y_test <span class="sc">-</span> pred.Btest2)<span class="sc">^</span><span class="dv">2</span>)  <span class="co"># Testing MSE</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Best lambda: "</span>, bestlamb.cv, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best lambda:  0.0224084 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">coef</span>(best_ridge))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>50 x 1 sparse Matrix of class "dgCMatrix"
                                       s0
(Intercept)                  6.478370e+00
(Intercept)                  .           
Institution.type            -3.084747e-03
Plurality.of.birth          -3.429659e-02
Gender                      -4.804617e-03
Race.of.child                3.808047e-04
RaceOther                    7.947638e-03
RaceWhite                    6.455639e-03
Age.of.father               -7.679371e-05
Age.of.mother                1.002633e-04
Education.of.father..years.  3.808010e-04
Education.of.mother..years.  4.342688e-04
Total.Preg                   9.235997e-04
BDead                       -2.406430e-02
Terms                       -1.366699e-03
Date.LBirth                 -4.986784e-10
Month.LBirth                -2.328507e-05
Year.LBirth                  3.108965e-06
LOutcome                    -1.891907e-04
Weeks                        1.828815e-02
Prenatal                     3.456070e-03
Trimester.Prenatal          -1.601978e-03
Visits                       1.621431e-03
Birth.weight.group           1.238124e-01
Marital                     -2.870645e-03
Birth.Attendant              5.054304e-04
Numchild                     2.665622e-03
Month.Term                  -7.218584e-04
Year.Term                    8.215467e-07
Low.BirthNorm                1.317013e-01
RaceMom                     -6.849657e-05
RaceDad                     -1.444243e-03
Mother.MinorityWhite         7.984752e-03
Father.MinorityWhite        -4.427625e-03
HispMomM                     1.217261e-03
HispMomN                    -1.696298e-03
HispMomO                    -1.099847e-02
HispMomP                    -1.272498e-03
HispMomS                     9.112568e-05
HispMomU                     2.279497e-02
HispDadM                    -1.532665e-03
HispDadN                    -3.089432e-04
HispDadO                     8.649688e-03
HispDadP                     1.692276e-03
HispDadS                     7.593321e-03
HispDadU                    -1.408813e-02
AveCigs                     -4.029724e-04
SmokerNo                     4.647282e-03
AveDrink                     2.408536e-04
Wt.Gain                      4.650144e-04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE: "</span>, MSE.births2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE:  0.006721434 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE: "</span>, MSE.Btest2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE:  0.006942309 </code></pre>
</div>
</div>
<p>The small lambda value of 0.022 tell us that more predictors contribute to the model.</p>
<p>The coefficients for each variable represent the contribution of that variable to the baby’s birth weight.</p>
<p>Positive coefficients (the highest being Weeks: 1.828815e-02 and Birth.weight.group: 1.238124e-01) indicate that increasing this variable is associated with a higher birth weight. Let me define these predictors: - Birth.weight.group: 00 if 500 grams or less, 01 if 501 – 1000 grams, … etc. - Weeks: Completed Weeks of Gestation; 18 – 45 Weeks</p>
<p>Negative coefficients (the lowest being Plurality.of.birth: -3.429659e-02 and HispDadU: -1.408813e-02) indicate that increasing this variable is associated with a lower birth weight. HispDadU means the hispanic origin of the father is unknown.</p>
<p>Lastly, variables with coefficients close to 0 have minimal impact on the prediction.</p>
<p>The training MSE, 0.0067214, is very samll. The testing MSE is also small - 0.0069423 - indicating that the model generalized well, has good prediction accuracy, and doesn’t over-fit the data.</p>
</section>
<section id="now-we-just-want-to-show-other-more-complex-techniques-and-how-they-can-make-a-difference.-here-we-will-try-lasso-regression-with-the-complete-data." class="level2">
<h2 class="anchored" data-anchor-id="now-we-just-want-to-show-other-more-complex-techniques-and-how-they-can-make-a-difference.-here-we-will-try-lasso-regression-with-the-complete-data.">Now we just want to show other more complex techniques and how they can make a difference. Here we will try Lasso Regression with the complete data.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare the data and do a log transformation</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>birthsLog <span class="ot">&lt;-</span> <span class="fu">transform</span>(births, <span class="at">lWeight =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(births<span class="sc">$</span>Birth.Weight..g.)))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>birthsLog <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthsLog, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Birth.Weight..g., X))  </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>births2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(birthsLog)  <span class="co"># remove NA's</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create model matrices with full and testing data</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>x_full <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lWeight <span class="sc">~</span> ., <span class="at">data =</span> births2) </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>y_full <span class="ot">&lt;-</span> births2<span class="sc">$</span>lWeight</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lWeight <span class="sc">~</span> ., <span class="at">data =</span> B.test2)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> B.test2<span class="sc">$</span>lWeight</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit lasso regression</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>lambda.v <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>model.lasso <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> lambda.v)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross-validation to find best lambda</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>cv.outputL <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>bestlamb.cvL <span class="ot">&lt;-</span> cv.outputL<span class="sc">$</span>lambda.min</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model with the best lambda</span></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>best_lasso <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_full, y_full, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> bestlamb.cvL)</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions</span></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>pred.lasso.train <span class="ot">&lt;-</span> <span class="fu">predict</span>(best_lasso, <span class="at">newx =</span> x_full, <span class="at">s =</span> bestlamb.cvL, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>pred.lasso.test <span class="ot">&lt;-</span> <span class="fu">predict</span>(best_lasso, <span class="at">newx =</span> x_test, <span class="at">s =</span> bestlamb.cvL, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MSE's</span></span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>train_mse_lasso <span class="ot">&lt;-</span> <span class="fu">mean</span>((y_full <span class="sc">-</span> pred.lasso.train)<span class="sc">^</span><span class="dv">2</span>)  <span class="co"># Full data MSE</span></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>test_mse_lasso <span class="ot">&lt;-</span> <span class="fu">mean</span>((y_test <span class="sc">-</span> pred.lasso.test)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Testing MSE</span></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Best Lambda (Lasso):"</span>, bestlamb.cvL, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best Lambda (Lasso): 0.0005815035 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE (Lasso):"</span>, train_mse_lasso, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE (Lasso): 0.006426799 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE (Lasso):"</span>, test_mse_lasso, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE (Lasso): 0.006627519 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot cross-validation results</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="fu">log</span>(cv.outputL<span class="sc">$</span>lambda), cv.outputL<span class="sc">$</span>cvm) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> cv.outputL<span class="sc">$</span>cvm <span class="sc">-</span> cv.outputL<span class="sc">$</span>cvsd, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> cv.outputL<span class="sc">$</span>cvm <span class="sc">+</span> cv.outputL<span class="sc">$</span>cvsd)) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Cross-Validation Error vs Lambda (Log Scale)"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Log(Lambda)"</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cross-Validation Error"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2-project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The lasso regression model has a slightly lower MSE than the ridge regression model (by about 0.0003), which shows that the shrinkage technique in Lasso regression can improve model generalization for this dataset.</p>
<p>Also, the plot shows the cross-validation error (the average prediction error during cross-validation) increasing rapidly as the log of lambda moves from -4 to 0. So as lambda increases, the model becomes overly regularized, leading to underfitting and poor performance</p>
</section>
<section id="summary-of-the-models-tested" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-the-models-tested">Summary of the models tested</h2>
<p>To summarize what we found, we need to know 2 definitions: - Bias: The error from the model’s assumptions. High bias means the model is too simple and misses important patterns (underfitting). - Flexibility: How well the model adapts to the data. High flexibility means the model can capture complex patterns, but too much flexibility can lead to overfitting, where the model includes noise in the data.</p>
<p>The multiple linear regression model uses all predictors, resulting in high bias and less flexibility, with training and testing MSE values of 721256.4 and 707930.6, respectively.</p>
<p>The stepwise regression model, selecting 8 predictors, has only a slightly better MSE (721443.2 and 709755.3) respectively.</p>
<p>Ridge regression, with a lambda of 0.00224, after a log transformation, achieves a training MSE of 0.006721434 and a testing MSE of 0.006942309 by applying penalties to predictors, balancing bias and flexibility. These MSE’s are better that what was shown in stepwise.</p>
<p>The Lasso model, with similar performance (training MSE: 0.00642802, Testing MSE: 0.006628631), further reduces predictors, offering higher flexibility and lower variance.</p>
<p>Based on the MSE values, Lasso Regression appears to be the best model. It has the lowest MSE on both the training (0.00642802) and testing sets (0.006628631), suggesting a good balance between bias and variance.</p>
</section>
<section id="so-what-about-these-predictors-in-terms-of-their-final-number-of-predictors-their-bias-and-their-flexibility" class="level2">
<h2 class="anchored" data-anchor-id="so-what-about-these-predictors-in-terms-of-their-final-number-of-predictors-their-bias-and-their-flexibility">So what about these predictors in terms of their final number of predictors, their bias and their flexibility?</h2>
<p>To answer this question, we need to know the definition of: Regularization: A technique to prevent overfitting by adding a penalty for complexity to the model. - Strong Regularization: Reduces the model’s flexibility, making it simpler. - Weak Regularization: Allows more flexibility, letting the model capture more details.</p>
<p>Ridge and Lasso regression handle regularization differently. Ridge reduces the size of all coefficients but keeps them in the model, which is great for balancing bias and variance. Lasso can shrink some coefficients to zero, which removes less important predictors and makes the model simpler. Ridge is better when you have many small, correlated effects, while Lasso works well when you want to focus on just the key predictors.</p>
</section>
<section id="instead-of-focusing-on-penalties-and-regularizing-we-can-remove-dimensions-and-correlations-by-testing-a-pcr-model-on-the-training-set." class="level2">
<h2 class="anchored" data-anchor-id="instead-of-focusing-on-penalties-and-regularizing-we-can-remove-dimensions-and-correlations-by-testing-a-pcr-model-on-the-training-set.">Instead of focusing on penalties and regularizing, we can remove dimensions and correlations by testing a PCR model on the training set.</h2>
<p>A principal component is a way to combine the original features in your data to find the most important patterns. The first one shows the most important patterns, and each next one shows less important details that are still there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pcrmodel <span class="ot">&lt;-</span> <span class="fu">pcr</span>(B.train<span class="sc">$</span>Birth.Weight..g.<span class="sc">~</span>., <span class="at">data=</span>B.train, <span class="at">scale=</span><span class="cn">TRUE</span>, <span class="at">validation=</span><span class="st">"CV"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pcrmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 5000 49 
    Y dimension: 5000 1
Fit method: svdpc
Number of components considered: 49

VALIDATION: RMSEP
Cross-validated using 10 random segments.
       (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
CV           611.4      610    607.9    603.6    503.5    334.6    306.5
adjCV        611.4      610    607.9    603.6    503.5    334.4    306.2
       7 comps  8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
CV       306.3    306.1    305.7     305.3     304.6     304.1     303.8
adjCV    306.2    305.9    305.8     305.1     304.5     304.0     303.7
       14 comps  15 comps  16 comps  17 comps  18 comps  19 comps  20 comps
CV        298.4     293.1     292.8     292.1     291.8     291.8     291.5
adjCV     298.3     292.9     292.6     291.9     291.6     291.6     291.4
       21 comps  22 comps  23 comps  24 comps  25 comps  26 comps  27 comps
CV        290.7     289.6     289.4     289.1     287.0     285.3     284.9
adjCV     290.6     289.3     289.3     289.0     286.9     284.9     284.8
       28 comps  29 comps  30 comps  31 comps  32 comps  33 comps  34 comps
CV        282.7     278.4     278.1     277.3     277.5     242.8     140.0
adjCV     282.3     277.9     277.9     277.0     277.5     275.3     139.6
       35 comps  36 comps  37 comps  38 comps  39 comps  40 comps  41 comps
CV        139.2     139.1     139.0     138.6     138.2     138.1     138.1
adjCV     139.0     139.0     138.9     138.5     138.1     138.0     138.0
       42 comps  43 comps  44 comps  45 comps  46 comps  47 comps  48 comps
CV        138.1     138.1     138.2     138.2     138.2     138.2     138.2
adjCV     138.1     138.1     138.1     138.1     138.1     138.1     138.1
       49 comps
CV        138.4
adjCV     138.1

TRAINING: % variance explained
                          1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
X                         11.8474   22.343   31.207    36.50    41.21    45.71
B.train$Birth.Weight..g.   0.4779    1.156    2.635    32.49    70.13    74.99
                          7 comps  8 comps  9 comps  10 comps  11 comps
X                            49.2    52.60    55.89     59.14     62.07
B.train$Birth.Weight..g.     75.0    75.07    75.07     75.31     75.36
                          12 comps  13 comps  14 comps  15 comps  16 comps
X                            64.78     67.27     69.53     71.71     73.80
B.train$Birth.Weight..g.     75.42     75.48     76.38     77.23     77.29
                          17 comps  18 comps  19 comps  20 comps  21 comps
X                            75.83     77.84     79.82     81.63     83.23
B.train$Birth.Weight..g.     77.45     77.55     77.55     77.60     77.73
                          22 comps  23 comps  24 comps  25 comps  26 comps
X                            84.78     86.27     87.53     88.73     89.92
B.train$Birth.Weight..g.     77.93     77.94     78.00     78.27     78.65
                          27 comps  28 comps  29 comps  30 comps  31 comps
X                            91.07     92.09     93.06     93.96     94.78
B.train$Birth.Weight..g.     78.66     79.07     79.72     79.74     79.87
                          32 comps  33 comps  34 comps  35 comps  36 comps
X                            95.56     96.23     96.85     97.39     97.85
B.train$Birth.Weight..g.     79.88     79.92     94.87     94.90     94.91
                          37 comps  38 comps  39 comps  40 comps  41 comps
X                            98.29     98.71     99.05     99.37     99.69
B.train$Birth.Weight..g.     94.91     94.95     94.99     94.99     94.99
                          42 comps  43 comps  44 comps  45 comps  46 comps
X                            99.85     99.99     99.99       100       100
B.train$Birth.Weight..g.     94.99     95.00     95.00        95        95
                          47 comps  48 comps  49 comps
X                              100       100       100
B.train$Birth.Weight..g.        95        95        95</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">validationplot</span>(pcrmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2-project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># choose 40 principle components based on analysis of summary of pcr model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># amount of variation explained by 40 principal components: 99.37% </span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to see the optimal M number of principal components </span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>optimal_M <span class="ot">&lt;-</span> <span class="fu">which.min</span>(pcrmodel<span class="sc">$</span>validation<span class="sc">$</span>PRESS)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions and find MSE's</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>train_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(pcrmodel, <span class="at">newdata =</span> B.train, <span class="at">ncomp =</span> optimal_M)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>MSE.Btrain <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.train<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> train_predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(pcrmodel,<span class="at">newdata =</span> B.test , <span class="at">ncomp =</span> optimal_M)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>MSE.Btest <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.test<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> test_predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Report the optimal M and MSE's</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Optimal M:"</span>, optimal_M, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimal M: 40 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE:"</span>, MSE.Btrain, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE: 18709.24 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE:"</span>, MSE.Btest, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE: 19207.04 </code></pre>
</div>
</div>
<p>The validation plot is a visualization for the optimal M by showing that the error is lowest beginning at around 38. 38 principal components means you’ve transformed your original features into 38 new variables (or dimensions) that capture the most important patterns in the data.</p>
<p>So, while the MSE’s in Lasso and Ridge Regression are much lower, PCR can still be valuable if the primary concern is reducing multicollinearity or performing dimensionality reduction.</p>
</section>
<section id="next-we-will-test-a-pls-model-which-also-performs-dimensionality-reduction-but-with-a-key-difference-in-how-the-components-are-selected." class="level2">
<h2 class="anchored" data-anchor-id="next-we-will-test-a-pls-model-which-also-performs-dimensionality-reduction-but-with-a-key-difference-in-how-the-components-are-selected.">Next, we will test a PLS model, which also performs dimensionality reduction, but with a key difference in how the components are selected.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>plsmodel <span class="ot">&lt;-</span> <span class="fu">plsr</span>(B.train<span class="sc">$</span>Birth.Weight..g.<span class="sc">~</span>., <span class="at">data=</span>B.train, <span class="at">scale=</span><span class="cn">TRUE</span>, <span class="at">validation=</span><span class="st">"CV"</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plsmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data:   X dimension: 5000 49 
    Y dimension: 5000 1
Fit method: kernelpls
Number of components considered: 49

VALIDATION: RMSEP
Cross-validated using 10 random segments.
       (Intercept)  1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
CV           611.4    285.3    248.4    197.6    162.2    146.8    141.4
adjCV        611.4    285.0    248.3    197.4    161.8    146.6    141.4
       7 comps  8 comps  9 comps  10 comps  11 comps  12 comps  13 comps
CV       138.8    138.3    138.2     138.2     138.2     138.3     138.3
adjCV    138.8    138.3    138.2     138.1     138.1     138.2     138.2
       14 comps  15 comps  16 comps  17 comps  18 comps  19 comps  20 comps
CV        138.3     138.3     138.3     138.3     138.3     138.3     138.3
adjCV     138.2     138.2     138.2     138.2     138.2     138.2     138.2
       21 comps  22 comps  23 comps  24 comps  25 comps  26 comps  27 comps
CV        138.3     138.3     138.3     138.3     138.3     138.3     138.3
adjCV     138.2     138.2     138.2     138.2     138.2     138.2     138.2
       28 comps  29 comps  30 comps  31 comps  32 comps  33 comps  34 comps
CV        138.3     138.3     138.3     138.3     138.3     138.3     138.3
adjCV     138.2     138.2     138.2     138.2     138.3     138.2     138.2
       35 comps  36 comps  37 comps  38 comps  39 comps  40 comps  41 comps
CV        138.3     138.3     138.3     138.3     138.3     138.3     138.3
adjCV     138.3     138.3     138.3     138.3     138.3     138.3     138.3
       42 comps  43 comps  44 comps  45 comps  46 comps  47 comps  48 comps
CV        138.3     138.3     138.3     138.3     138.3     138.3     138.3
adjCV     138.3     138.3     138.3     138.3     138.2     138.2     138.2
       49 comps
CV        138.3
adjCV     138.2

TRAINING: % variance explained
                          1 comps  2 comps  3 comps  4 comps  5 comps  6 comps
X                           5.585    15.15    20.14    26.76    32.35    39.33
B.train$Birth.Weight..g.   78.466    83.66    89.78    93.17    94.37    94.76
                          7 comps  8 comps  9 comps  10 comps  11 comps
X                           43.83    45.97    48.90     52.03     53.96
B.train$Birth.Weight..g.    94.95    94.99    94.99     94.99     95.00
                          12 comps  13 comps  14 comps  15 comps  16 comps
X                            55.52      57.5     59.42     61.21     62.78
B.train$Birth.Weight..g.     95.00      95.0     95.00     95.00     95.00
                          17 comps  18 comps  19 comps  20 comps  21 comps
X                            64.59     66.67     68.34     70.63     72.17
B.train$Birth.Weight..g.     95.00     95.00     95.00     95.00     95.00
                          22 comps  23 comps  24 comps  25 comps  26 comps
X                            73.83     75.04     76.28     77.71     79.09
B.train$Birth.Weight..g.     95.00     95.00     95.00     95.00     95.00
                          27 comps  28 comps  29 comps  30 comps  31 comps
X                            81.23     82.88     83.89     85.07     86.27
B.train$Birth.Weight..g.     95.00     95.00     95.00     95.00     95.00
                          32 comps  33 comps  34 comps  35 comps  36 comps
X                            87.65     88.55     89.26     90.46     91.37
B.train$Birth.Weight..g.     95.00     95.00     95.00     95.00     95.00
                          37 comps  38 comps  39 comps  40 comps  41 comps
X                            92.52     93.49     94.46     95.91      97.2
B.train$Birth.Weight..g.     95.00     95.00     95.00     95.00      95.0
                          42 comps  43 comps  44 comps  45 comps  46 comps
X                            97.95     98.45     99.39       100     100.1
B.train$Birth.Weight..g.     95.00     95.00     95.00        95      95.0
                          47 comps  48 comps  49 comps
X                            100.2     100.3     100.5
B.train$Birth.Weight..g.      95.0      95.0      95.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">validationplot</span>(plsmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2-project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># choose 10 principal components (from summary analysis)</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># amount of variation explained by 10 principal components: 94.99%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to see the optimal M and the amount of variation</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>optimal_M <span class="ot">&lt;-</span> <span class="fu">which.min</span>(plsmodel<span class="sc">$</span>validation<span class="sc">$</span>PRESS)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>explained_variance <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">explvar</span>(plsmodel))</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>train_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(plsmodel, <span class="at">newdata =</span> B.train, <span class="at">ncomp =</span> optimal_M)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>MSE.Btrain <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.train<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> train_predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(plsmodel,<span class="at">newdata =</span> B.test , <span class="at">ncomp =</span> optimal_M)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>MSE.Btest <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.test<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> test_predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Optimal M:"</span>, optimal_M, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimal M: 10 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cat("Amount of Variance explained by the optimal M:", explained_variance, "\n")</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE:"</span>, MSE.Btrain, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE: 18701.52 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE:"</span>, MSE.Btest, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE: 19238.18 </code></pre>
</div>
</div>
<p>The MSE’s are roughly equal, but the validation plot shows that the error is lowest beginning at a little before 10 principal components.</p>
</section>
<section id="lastly-we-will-fit-a-gam-on-the-training-and-testing-data." class="level2">
<h2 class="anchored" data-anchor-id="lastly-we-will-fit-a-gam-on-the-training-and-testing-data.">Lastly, we will fit a GAM on the training and testing data.</h2>
<p>Unlike linear regression, where relationships are assumed to be linear, a Generalized Additive Model (GAM) can model non-linear relationships by using smooth (not necessarily linear) functions for each predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model on the training data with the significant predictors</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>gammodel <span class="ot">&lt;-</span> <span class="fu">gam</span>(B.train<span class="sc">$</span>Birth.Weight..g. <span class="sc">~</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">s</span>(Weeks) <span class="sc">+</span> </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">s</span>(Wt.Gain) <span class="sc">+</span> </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>                  Plurality.of.birth <span class="sc">+</span> Gender <span class="sc">+</span> Race <span class="sc">+</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>                  Birth.weight.group <span class="sc">+</span> Father.Minority <span class="sc">+</span> Smoker, </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> B.train)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gammodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
B.train$Birth.Weight..g. ~ s(Weeks) + s(Wt.Gain) + Plurality.of.birth + 
    Gender + Race + Birth.weight.group + Father.Minority + Smoker

Parametric coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           528.934     20.235  26.139  &lt; 2e-16 ***
Plurality.of.birth    -37.088     10.774  -3.442 0.000582 ***
Gender                 -9.625      3.921  -2.455 0.014128 *  
RaceOther              10.493     10.307   1.018 0.308749    
RaceWhite              22.275      9.578   2.326 0.020073 *  
Birth.weight.group    455.856      2.042 223.264  &lt; 2e-16 ***
Father.MinorityWhite    5.287      8.804   0.601 0.548183    
SmokerNo               27.350      6.716   4.072 4.73e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf Ref.df      F p-value    
s(Weeks)   2.901  3.669 47.305 &lt; 2e-16 ***
s(Wt.Gain) 2.039  2.608  4.177 0.00733 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =   0.95   Deviance explained =   95%
GCV =  18881  Scale est. = 18832     n = 5000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and find the training MSE</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>train_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(gammodel, <span class="at">newdata =</span> B.train)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>train_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.train<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> train_predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training MSE:"</span>, train_mse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training MSE: 18783.65 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>B.train<span class="sc">$</span>Predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(gammodel, <span class="at">newdata =</span> B.train)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(B.train, <span class="fu">aes</span>(<span class="at">x =</span> Birth.Weight..g., <span class="at">y =</span> Predicted)) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Actual vs Predicted Birth Weight"</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Actual Birth Weight (grams)"</span>,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Birth Weight (grams)"</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2-project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The actual vs.&nbsp;predicted weights plot shows that the GAM model fits the training data very well. It accurately predicts the baby weights given the significant predictors chosen from the step BIC function.</p>
</section>
<section id="evaluate-the-model-obtained-on-the-testing-data-set" class="level2">
<h2 class="anchored" data-anchor-id="evaluate-the-model-obtained-on-the-testing-data-set">Evaluate the model obtained on the testing data set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>gammodel2 <span class="ot">&lt;-</span> <span class="fu">gam</span>(Birth.Weight..g. <span class="sc">~</span> Plurality.of.birth <span class="sc">+</span> Gender <span class="sc">+</span> Race <span class="sc">+</span> <span class="fu">s</span>(Weeks, <span class="at">k =</span> <span class="dv">5</span>) <span class="sc">+</span> Birth.weight.group <span class="sc">+</span> Father.Minority <span class="sc">+</span> Smoker <span class="sc">+</span> <span class="fu">s</span>(Wt.Gain, <span class="at">k =</span> <span class="dv">5</span>),<span class="at">data =</span> B.test)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gammodel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
Birth.Weight..g. ~ Plurality.of.birth + Gender + Race + s(Weeks, 
    k = 5) + Birth.weight.group + Father.Minority + Smoker + 
    s(Wt.Gain, k = 5)

Parametric coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           545.643     27.234  20.036  &lt; 2e-16 ***
Plurality.of.birth    -45.572     14.717  -3.097  0.00198 ** 
Gender                 -7.759      5.247  -1.479  0.13934    
RaceOther              -9.130     13.398  -0.681  0.49566    
RaceWhite               4.800     12.478   0.385  0.70052    
Birth.weight.group    455.873      2.775 164.297  &lt; 2e-16 ***
Father.MinorityWhite   10.143     11.369   0.892  0.37238    
SmokerNo               29.653      9.458   3.135  0.00173 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf Ref.df      F p-value    
s(Weeks)   3.201  3.608 21.100  &lt;2e-16 ***
s(Wt.Gain) 1.000  1.000  5.552  0.0185 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.947   Deviance explained = 94.8%
GCV =  19248  Scale est. = 19166     n = 2861</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>B.test<span class="sc">$</span>Predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(gammodel2, <span class="at">newdata =</span> B.test)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>test_mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((B.test<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> B.test<span class="sc">$</span>Predicted)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>ss_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((B.test<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> <span class="fu">mean</span>(B.test<span class="sc">$</span>Birth.Weight..g.))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>ss_residual <span class="ot">&lt;-</span> <span class="fu">sum</span>((B.test<span class="sc">$</span>Birth.Weight..g. <span class="sc">-</span> B.test<span class="sc">$</span>Predicted)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (ss_residual <span class="sc">/</span> ss_total)</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(B.test, <span class="fu">aes</span>(<span class="at">x =</span> Birth.Weight..g., <span class="at">y =</span> Predicted)) <span class="sc">+</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Actual vs Predicted Birth Weight (Testing Data)"</span>,</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"Actual Birth Weight (grams)"</span>,</span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Predicted Birth Weight (grams)"</span></span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2-project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing MSE:"</span>, test_mse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing MSE: 19084.45 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Testing R-squared:"</span>, r_squared, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing R-squared: 0.9476297 </code></pre>
</div>
</div>
<p>The GAM model fits the testing data very well with a high r squared, and the the model does not overfit as the testing MSE is similar to the training MSE. The testing MSE is higher than the training, as expected.</p>
</section>
<section id="which-of-the-predictor-variables-has-evidence-of-a-non-linear-relationship-with-the-response-variable" class="level2">
<h2 class="anchored" data-anchor-id="which-of-the-predictor-variables-has-evidence-of-a-non-linear-relationship-with-the-response-variable">Which of the predictor variables has evidence of a non-linear relationship with the response variable?</h2>
<p>“Weeks” shows evidence of a non-linear relationship with birth weight, with a very low p-value in both GAM summaries. “Wt.Gain” shows a weak non-linear relationship with a p value closer to 0.05, suggesting it is closer to linear but not completely.</p>
</section>
<section id="and-thats-it.-i-hope-you-enjoyed-seeing-some-applications-of-machine-learning-models-onto-an-interesting-data-set." class="level2">
<h2 class="anchored" data-anchor-id="and-thats-it.-i-hope-you-enjoyed-seeing-some-applications-of-machine-learning-models-onto-an-interesting-data-set.">And that’s it. I hope you enjoyed seeing some applications of machine learning models onto an interesting data set.</h2>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>© 2024, Fathima Shaikh</p>
</div>
  </div>
</footer>




</body></html>